# Generated by Django 6.0.5 on 2026-05-16 16:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demosite', '0003_blogentrypagetag_fk_for_django_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Page title (rich text)'),
        ),
    ]
