# Generated by Django 6.0.5 on 2026-05-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
    ]
