# Generated by Django 6.0.5 on 2026-05-17 19:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='display_title',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional styled title to display instead of the plain page title.'),
        ),
    ]
