# Generated by Django 6.0.5 on 2026-05-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpage_display_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='display_title',
        ),
    ]
