# Generated by Django 6.0.5 on 2026-05-17 20:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_blogindexpage_body_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 2), ('image', 5), ('thumbnail', 5), ('quote', 6), ('section', 9), ('two_columns', 12), ('three_columns', 13)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full width')], 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('alignment', 0), ('content', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('alignment', 0)]], {}), 6: ('wagtail.blocks.StructBlock', [[('content', 1), ('alignment', 0)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('dark', 'Dark'), ('accent', 'Accent')]}), 9: ('wagtail.blocks.StructBlock', [[('heading', 7), ('body', 1), ('theme', 8), ('alignment', 0)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1-1', '50% / 50%'), ('2-1', '66% / 33%'), ('1-2', '33% / 66%')], 'label': 'Column ratio'}), 11: ('wagtail.blocks.StreamBlock', [[('rich_text', 2), ('image', 5), ('thumbnail', 5), ('quote', 6)]], {}), 12: ('wagtail.blocks.StructBlock', [[('layout', 10), ('left', 11), ('right', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('left', 11), ('center', 11), ('right', 11)]], {})}),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 2), ('image', 5), ('thumbnail', 5), ('quote', 6), ('section', 9), ('two_columns', 12), ('three_columns', 13)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full width')], 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('alignment', 0), ('content', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('alignment', 0)]], {}), 6: ('wagtail.blocks.StructBlock', [[('content', 1), ('alignment', 0)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('dark', 'Dark'), ('accent', 'Accent')]}), 9: ('wagtail.blocks.StructBlock', [[('heading', 7), ('body', 1), ('theme', 8), ('alignment', 0)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1-1', '50% / 50%'), ('2-1', '66% / 33%'), ('1-2', '33% / 66%')], 'label': 'Column ratio'}), 11: ('wagtail.blocks.StreamBlock', [[('rich_text', 2), ('image', 5), ('thumbnail', 5), ('quote', 6)]], {}), 12: ('wagtail.blocks.StructBlock', [[('layout', 10), ('left', 11), ('right', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('left', 11), ('center', 11), ('right', 11)]], {})}),
        ),
    ]
