# Generated by Django 6.0.5 on 2026-05-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogindexpage_subheader_fields'),
        ('blog', '0018_fix_card_style_to_blogindexpage'),
    ]

    operations = [
    ]
