# Generated by Django 6.0.5 on 2026-05-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_blogindexpage_body_alter_blogpage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='header_bg_color',
            field=models.CharField(blank=True, default='', help_text='Overrides the nav bar background colour on this page. Any valid CSS colour. Leave blank for the site default.', max_length=32, verbose_name='Header background colour'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='header_bg_color',
            field=models.CharField(blank=True, default='', help_text='Overrides the nav bar background colour on this page. Any valid CSS colour. Leave blank for the site default.', max_length=32, verbose_name='Header background colour'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='subheader_bg_color',
            field=models.CharField(blank=True, default='', help_text='Any valid CSS colour. Leave blank to hide the subheader strip.', max_length=32, verbose_name='Subheader background colour'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='subheader_image',
            field=models.ForeignKey(blank=True, help_text='Centred image displayed inside the coloured subheader strip.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Subheader image'),
        ),
    ]
