# Generated by Django 6.0.6 on 2026-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_blogindexpage_body_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='subheader_bg_color',
            field=models.CharField(blank=True, default='', help_text='Any valid CSS colour: hex (#1a2b3c), rgb(), named colour, etc. Leave blank to hide the subheader strip.', max_length=32, verbose_name='Subheader background colour'),
        ),
    ]
