# Generated by Django 6.0.5 on 2026-05-17 01:41

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('quote', 1), ('section', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'openquote', 'template': 'home/blocks/quote.html'}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('dark', 'Dark'), ('accent', 'Accent')]}), 5: ('wagtail.blocks.StructBlock', [[('heading', 2), ('body', 3), ('theme', 4)]], {'icon': 'form', 'template': 'home/blocks/section.html'})}),
        ),
    ]
