# Generated by Django 6.0.5 on 2026-05-17 02:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_intro_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 3), ('quote', 4), ('section', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {'icon': 'image', 'template': 'home/blocks/image.html'}), 4: ('wagtail.blocks.RichTextBlock', (), {'icon': 'openquote', 'template': 'home/blocks/quote.html'}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.RichTextBlock', (), {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('dark', 'Dark'), ('accent', 'Accent')]}), 8: ('wagtail.blocks.StructBlock', [[('heading', 5), ('body', 6), ('theme', 7)]], {'icon': 'form', 'template': 'home/blocks/section.html'})}),
        ),
    ]
