# Generated by Django 6.0.5 on 2026-05-17 12:01

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=wagtail.fields.RichTextField(blank=True, default='Neil Whittaker. Built with Wagtail.', verbose_name='Footer text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
