# Generated by Django 6.0.5 on 2026-05-17 20:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homepage_display_title'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('image', 3), ('thumbnail', 4), ('quote', 5), ('section', 9)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {'icon': 'image', 'template': 'home/blocks/image.html'}), 4: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {'icon': 'image', 'template': 'home/blocks/thumbnail.html'}), 5: ('wagtail.blocks.RichTextBlock', (), {'icon': 'openquote', 'template': 'home/blocks/quote.html'}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.RichTextBlock', (), {}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('dark', 'Dark'), ('accent', 'Accent')]}), 9: ('wagtail.blocks.StructBlock', [[('heading', 6), ('body', 7), ('theme', 8)]], {'icon': 'form', 'template': 'home/blocks/section.html'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
