# Generated by Django 6.0.5 on 2026-05-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_body_alter_standardpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_css_classes',
            field=models.CharField(blank=True, help_text="Space-separated CSS classes to apply to the page title <h1>, e.g. 'text-hero text-center u-color-accent'", max_length=255, verbose_name='Title CSS classes'),
        ),
    ]
