# Generated by Django 6.0.5 on 2026-05-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_homepage_title_css_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header_icon_css_classes',
            field=models.CharField(blank=True, help_text="Space-separated CSS classes on the header icon image, e.g. 'rounded-full'", max_length=255, verbose_name='Header icon CSS classes'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, help_text='Overrides the Wagtail site name shown in the header. Leave blank to use the default.', max_length=255, verbose_name='Site name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_css_classes',
            field=models.CharField(blank=True, help_text="Space-separated CSS classes on the site name text, e.g. 'text-xl font-bold u-color-accent'", max_length=255, verbose_name='Site name CSS classes'),
        ),
    ]
