# Generated by Django 5.2.14 on 2026-05-20 06:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_standardpage_subheader_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rich_title',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional. Replaces the plain title on the page. Supports bold, italic, links. Leave blank to use the plain title above.', verbose_name='Display title (rich text)'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='rich_title',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional. Replaces the plain title on the page. Supports bold, italic, links. Leave blank to use the plain title above.', verbose_name='Display title (rich text)'),
        ),
    ]
