# Generated by Django 5.2.14 on 2026-05-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homepage_rich_title_standardpage_rich_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='rich_title',
        ),
    ]
