# Generated by Django 6.0.5 on 2026-05-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_homepage_body_alter_standardpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagtailshaderpage',
            name='shader_type',
            field=models.CharField(choices=[('gradient', 'Animated Gradient'), ('wave', 'Wave Distortion'), ('noise', 'Noise / FBM'), ('accretion', 'Accretion (XorDev)')], default='gradient', help_text='Which GPU shader effect to display in the hero canvas.', max_length=32, verbose_name='Shader type'),
        ),
    ]
