# Generated by Django 6.0.5 on 2026-05-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_wagtailshaderpage_shader_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagtailshaderpage',
            name='body_bg_color',
            field=models.CharField(blank=True, default='', help_text='Overrides the page background colour. Any valid CSS colour (e.g. #0a0a1a, #ffffff, rgb(10,10,26)). Leave blank for the site default.', max_length=32, verbose_name='Body background colour'),
        ),
        migrations.AddField(
            model_name='wagtailshaderpage',
            name='body_text_color',
            field=models.CharField(blank=True, default='', help_text='Overrides the body text colour. Any valid CSS colour (e.g. #ffffff, #1a1a1a). Leave blank for the site default.', max_length=32, verbose_name='Body text colour'),
        ),
    ]
