# Generated by Django 6.0.5 on 2026-05-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_wagtailshaderpage_body_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_bg_color',
            field=models.CharField(blank=True, default='', help_text='Any valid CSS colour (e.g. #0a0a1a, #ffffff). Leave blank for the site default.', max_length=32, verbose_name='Body background colour'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_text_color',
            field=models.CharField(blank=True, default='', help_text='Any valid CSS colour (e.g. #ffffff, #1a1a1a). Leave blank for the site default.', max_length=32, verbose_name='Body text colour'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='shader_height',
            field=models.IntegerField(default=400, help_text='Height of the shader canvas in pixels. Recommended: 300–600.', verbose_name='Canvas height (px)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='shader_type',
            field=models.CharField(blank=True, choices=[('', '— None (no shader) —'), ('gradient', 'Animated Gradient'), ('wave', 'Wave Distortion'), ('noise', 'Noise / FBM'), ('accretion', 'Accretion (XorDev)')], default='', help_text='Choose a shader to display as a full-width hero above the page content. Leave blank to use the standard subheader strip instead.', max_length=32, verbose_name='Shader type'),
        ),
    ]
