# Generated by Django 5.2.15 on 2026-06-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_homepage_body_bg_color_homepage_body_text_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_headline',
            field=models.CharField(blank=True, help_text="Large text displayed over the shader. E.g. 'Guitar Resources for Serious Players'", max_length=255, verbose_name='Hero headline'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_strapline',
            field=models.CharField(blank=True, help_text='Smaller subtitle beneath the headline. Leave blank to show headline only.', max_length=255, verbose_name='Hero strapline'),
        ),
    ]
